// Code generated by "stringer -type=TypeParser"; DO NOT EDIT.

package factory

import "strconv"

const _TypeParser_name = "ttndingnet"

var _TypeParser_index = [...]uint8{0, 3, 10}

func (i TypeParser) String() string {
	if i < 0 || i >= TypeParser(len(_TypeParser_index)-1) {
		return "TypeParser(" + strconv.FormatInt(int64(i), 10) + ")"
	}
	return _TypeParser_name[_TypeParser_index[i]:_TypeParser_index[i+1]]
}
